#!/usr/bin/env python3
"""
Turn the values from the TTN console into a config file for one lamp.

  python3 tools/make_config.py            # asks for each value
  python3 tools/make_config.py --lamp 2   # ...for the second lamp

Writes firmware/config.lamp<N>.py, which is gitignored. Deploy it with:

  ./tools/deploy.sh --lamp 1 /dev/ttyACM0

Why bother with a tool for six values: three of the ways to get this
wrong produce a lamp that joins the network perfectly and then does
nothing, with no error anywhere that says why.

  * both lamps sharing a DevEUI      -> the second one steals the session
  * the lamps having DIFFERENT JoinEUIs -> one of them never joins
  * both lamps sharing a LAMP_ID     -> they join fine, then deliberately
                                        ignore each other forever, because
                                        the CRDT treats a message bearing
                                        your own id as an echo of yourself

So this checks the new lamp against any sibling config already written.
"""
import argparse
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FIRMWARE = os.path.join(ROOT, "firmware")

HEX = re.compile(r"^[0-9A-Fa-f]+$")


def clean(value):
    """TTN's copy buttons sometimes include spaces or 0x. Strip them."""
    return value.strip().replace(" ", "").replace("0x", "").replace("0X", "")


def ask_hex(prompt, length, default=None):
    while True:
        suffix = " [%s]" % default if default else ""
        raw = input("  %s%s: " % (prompt, suffix)).strip()
        if not raw and default:
            return default
        value = clean(raw)
        if len(value) != length:
            print("    needs %d hex characters, got %d" % (length, len(value)))
            continue
        if not HEX.match(value):
            print("    that is not hex — copy it from the TTN console")
            continue
        return value.upper()


def ask_int(prompt, lo, hi, default=None):
    while True:
        suffix = " [%s]" % default if default is not None else ""
        raw = input("  %s%s: " % (prompt, suffix)).strip()
        if not raw and default is not None:
            return default
        try:
            value = int(raw)
        except ValueError:
            print("    needs a number")
            continue
        if not (lo <= value <= hi):
            print("    must be between %d and %d" % (lo, hi))
            continue
        return value


def read_existing(path):
    """Pull the values back out of a config we wrote earlier."""
    found = {}
    try:
        with open(path) as f:
            for line in f:
                m = re.match(r'\s*(LAMP_ID|LORA_DEV_EUI|LORA_APP_EUI|'
                             r'LORA_APP_KEY)\s*=\s*"?([^"#\s]+)"?', line)
                if m:
                    found[m.group(1)] = m.group(2)
    except OSError:
        return None
    return found or None


def siblings(this_lamp):
    """Every other lamp config already written, for cross-checking."""
    out = {}
    for name in sorted(os.listdir(FIRMWARE)):
        m = re.match(r"config\.lamp(\d+)\.py$", name)
        if not m or int(m.group(1)) == this_lamp:
            continue
        values = read_existing(os.path.join(FIRMWARE, name))
        if values:
            out[int(m.group(1))] = values
    return out


TEMPLATE = '''# ============================================================
#  config.py  —  lamp {lamp_id} ({name})
#  Generated by tools/make_config.py. Never committed.
# ============================================================

LAMP_ID   = {lamp_id}
LAMP_NAME = "{name}"

# ── LoRaWAN (The Things Network) ────────────────────────────
LORA_ENABLED = True
LORA_DEV_EUI = "{dev_eui}"      # unique to this lamp
LORA_APP_EUI = "{app_eui}"      # SAME on every lamp in the group
LORA_APP_KEY = "{app_key}"
LORA_REGION  = "{region}"
LORA_CLASS   = "C"              # mains-powered: receives at any time
LORA_PORT    = 8

LORA_UART_ID = 1
LORA_TX_PIN  = {tx}
LORA_RX_PIN  = {rx}
LORA_BAUD    = 9600

# Ten downlinks a day is your FRIEND's limit, and every uplink the bridge
# forwards spends one. 2 heartbeats + 8 changes = 10.
LORA_MIN_INTERVAL_MS = 3 * 60 * 60 * 1000

# ── WiFi (optional) ─────────────────────────────────────────
WIFI_ENABLED  = {wifi_enabled}
WIFI_NETWORKS = {wifi_networks}

MQTT_BROKER   = ""
MQTT_PORT     = 1883
MQTT_USER     = ""
MQTT_PASSWORD = ""
MQTT_PREFIX   = "friendlights_{prefix}"

# ── LED strip ───────────────────────────────────────────────
LED_PIN        = {led_pin}
NUM_LEDS       = {num_leds}
LED_BRIGHTNESS = 0.6
LED_ORDER      = "{led_order}"
REVERSE_LEDS   = False

# ── Touch ───────────────────────────────────────────────────
TOUCH_PINS      = {touch_pins}
TOUCH_THRESHOLD = 20000

# ── Feel ────────────────────────────────────────────────────
ARRIVAL_FADE_MS = 90 * 1000
BREATHE_SPEED   = 0.0008
BREATHE_DEPTH   = 0.04

PORTAL_ENABLED   = True
WATCHDOG_ENABLED = True
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lamp", type=int, help="lamp number (1, 2, ...)")
    ap.add_argument("--force", action="store_true",
                    help="overwrite an existing config for this lamp")
    args = ap.parse_args()

    print("\n  Setting up a lamp. Values come from the TTN console:")
    print("  Applications -> your app -> End devices -> the device.\n")

    lamp_id = args.lamp or ask_int("Lamp number (1 or 2)", 1, 255, 1)
    path = os.path.join(FIRMWARE, "config.lamp%d.py" % lamp_id)
    if os.path.exists(path) and not args.force:
        print("\n  %s already exists. Use --force to replace it.\n"
              % os.path.relpath(path, ROOT))
        return 1

    others = siblings(lamp_id)
    if others:
        print("  Cross-checking against lamp %s.\n"
              % ", ".join(str(k) for k in sorted(others)))

    name = input("  A name for it (e.g. Zurich): ").strip() or "lamp%d" % lamp_id

    # JoinEUI is shared, so offer whatever a sibling already uses.
    shared_eui = None
    for v in others.values():
        shared_eui = v.get("LORA_APP_EUI")
        break

    print()
    dev_eui = ask_hex("DevEUI          (16 hex)", 16)
    app_eui = ask_hex("JoinEUI/AppEUI  (16 hex)", 16,
                      default=shared_eui or "0011223344556677")
    app_key = ask_hex("AppKey          (32 hex)", 32)

    print("\n  Hardware — press enter to accept the defaults from the README.")
    led_pin = ask_int("LED data pin", 0, 48, 2)
    num_leds = ask_int("Number of LEDs", 1, 300, 10)
    order = input("  Strip type [GRBW for SK6812, GRB for WS2812]: ").strip()
    led_order = order.upper() if order else "GRBW"
    touch = ask_int("Touch pin (0 for none)", 0, 48, 4)

    print()
    ssid = input("  WiFi SSID (optional, enter to skip): ").strip()
    password = ""
    if ssid:
        password = input("  WiFi password: ").strip()

    # ── The checks that matter ──
    problems = []
    for other_id, other in sorted(others.items()):
        if other.get("LORA_DEV_EUI") == dev_eui:
            problems.append(
                "DevEUI is identical to lamp %d. Each device needs its own — "
                "sharing one means they fight over the same session and "
                "neither stays joined." % other_id)
        if other.get("LORA_APP_KEY") == app_key:
            problems.append(
                "AppKey is identical to lamp %d. Generate a separate one."
                % other_id)
        if shared_eui and app_eui != shared_eui:
            problems.append(
                "JoinEUI differs from lamp %d (%s). It identifies the join "
                "server, not the lamp, so it must be the SAME on both."
                % (other_id, other.get("LORA_APP_EUI")))
    if dev_eui == "0" * 16:
        problems.append("DevEUI is all zeros — let TTN generate a real one.")
    if app_key == "0" * 32:
        problems.append("AppKey is all zeros — that is the actual secret.")

    if problems:
        print("\n  Not writing the file:\n")
        for p in problems:
            print("    - %s" % p)
        print()
        return 1

    if app_eui == "0" * 16:
        print("\n  Note: an all-zero JoinEUI is allowed by TTN, but some "
              "\n  LoRaWAN stacks read it as 'not configured' and refuse to "
              "\n  join, with no error saying so. A made-up value is safer.")

    body = TEMPLATE.format(
        lamp_id=lamp_id, name=name,
        dev_eui=dev_eui, app_eui=app_eui, app_key=app_key,
        region="EU868", tx=43, rx=44,
        wifi_enabled=bool(ssid),
        wifi_networks=repr([[ssid, password]]) if ssid else "[]",
        prefix=name.lower().replace(" ", "_"),
        led_pin=led_pin, num_leds=num_leds, led_order=led_order,
        touch_pins=repr([touch]) if touch else "[]")

    with open(path, "w") as f:
        f.write(body)

    print("\n  Wrote %s" % os.path.relpath(path, ROOT))
    print("\n  Check it matches the TTN console, then:")
    print("    ./tools/deploy.sh --lamp %d /dev/ttyACM0\n" % lamp_id)
    if len(others) == 0:
        print("  Then run this again with --lamp %d for the other one.\n"
              % (2 if lamp_id == 1 else 1))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (KeyboardInterrupt, EOFError):
        print("\n  cancelled\n")
        sys.exit(1)
